### ISSUE TITLE
Will v1 Implementation happen?

### ISSUE THREAD

**Issue by tottes200** [panoramicdata/Meraki.Api#1]
Hello,
I'm super excited to find this and thank you for your efforts. Are you planning on updating this for the v1 API that they just released?

**Comment by davidnmbond** [comment]
Hi there tottes200...

We're glad you find it useful!

This represents a significant dev effort and we have no funding to develop v1 at present.  Perhaps someone from Meraki will see this and fund us a few days?

**Comment by danielabbatt** [comment]
v1 is now published as of nuget package v1.11 e.g. https://www.nuget.org/packages/Meraki.Api/1.11.4
There are some breaking changes but it should be fairly logical fixing things.
