### ISSUE TITLE
Issue with fields parameter in GetNetworkSmDevicesAsync call.

### ISSUE THREAD

**Issue by speed2048** [panoramicdata/Meraki.Api#101]
The following code snippet returns the following Exception  {"errors":["'fields' must be an array"]} 

`
                List<string> fields = new();
                fields.Add("batteryEstCharge");

                var smDevices = await merakiClient
                           .Sm
                           .Devices
                           .GetNetworkSmDevicesAsync(smNetworkID, fields)
                           .ConfigureAwait(false);
`
Postman executes successfully and the URL is: 

{baseUrl}}/networks/{networkid}/sm/devices?fields[]=batteryEstCharge

I tried doing:

fields.add( "fields[]=batteryEstCharge"); to no avail.

I did a trace of what your API is sending to Meraki:

trce: XPORestAPI.Controllers.MerakiController[0]
      Request c9022dea-b1d2-47cc-ae12-1aa76e526fcb: Request
      Method: GET, RequestUri: 'https://api.meraki.com/api/v1/networks/{networkid}/sm/devices?fields=batteryEstCharge&perPage=1000', Version: 1.1, Content: <null>, Headers:

From what I am seeing the fields is missing the array designator []. so it should be sending
fields[]

Or am I doing something wrong?

Please advise.

Regards,
Bob

**Comment by danielabbatt** [comment]
The library is using refit under the hood and I believe it sends multi-value query string parameters in this way: 
devices?fields=name1&fields=name2
hence if you're only sending one thing with fields.Add("batteryEstCharge") I would expect it to send
devices?fields=name1
I understand from you however that the Meraki API isn't respecting this format so I'll have to have a look into it and see.

**Comment by danielabbatt** [comment]
This format is in fact what the curl template uses, it will use a comma separated string, which is another value format, but a single value gets sent as I expect, so it's possible the Meraki API is misbehaving, wouldn't be a first.

![image](https://user-images.githubusercontent.com/8926756/225254556-6ea56b04-1d04-4b16-a0e1-4d44ccb3ad0f.png)

**Comment by speed2048** [comment]
Hi Daniel,

I agree the Meraki API misbehaves and the documentation might be out of date. As the only way to return the extra fields is to change fields to  fields[].

I have found a way to get additional attributes for the SM devices:

In ISmDevices.cs  I modified the fields parameter to this.


Task<List<SmDevice>> GetNetworkSmDevicesAsync(

		[AliasAs("networkId")] string networkId,
		**[AliasAs("fields[]")] string fields = null!**, ...

I modifed SmDevice.cs to add the attributes that I needed. For estimated battery Charge.

[ApiAccess(ApiAccess.Read)]
	[DataMember(Name = "batteryEstCharge")]
	public string batteryEstCharge { get; set; } = string.Empty;

Also changed my code to:
`
 string fields = "batteryEstCharge";  //Comma seprated string to get additional fields.

                var smDevices = await merakiClient
                           .Sm
                           .Devices
                           .GetNetworkSmDevicesAsync(smNetworkID, fields)
                           .ConfigureAwait(false);
`

I believe you will need to map the other attributes in SmDevice.cs.

Regards,
Bob

**Comment by danielabbatt** [comment]
I've committed this as a change and updated the other query params. Looking into it further, but should be working for you in the next release 1.30.21+

**Comment by speed2048** [comment]
Hi Daniel,

I was able to get the batteryEstCharge attribute from the updated package but there are others ( I don't need  all but might as well map them) that I need that is from the additional list. As documented by Meraki and is in your comments in SmDevice.. They are:

The additional fields are: ip,     systemType, availableDeviceCapacity, kioskAppName, biosVersion, lastConnected, missingAppsCount, userSuppliedAddress, location, lastUser,     ownerEmail, ownerUsername, publicIp, phoneNumber, diskInfoJson, deviceCapacity, isManaged, hadMdm, isSupervised, meid, imei, iccid,     simCarrierNetwork, cellularDataUsed, isHotspotEnabled, createdAt, batteryEstCharge, quarantined, avName, avRunning, asName, fwName,     isRooted, loginRequired, screenLockEnabled, screenLockDelay, autoLoginDisabled, autoTags, hasMdm, hasDesktopAgent, diskEncryptionEnabled,     hardwareEncryptionCaps, passCodeLock, usesHardwareKeystore, and androidSecurityPatchVersion.

Regards,
Bob

**Comment by danielabbatt** [comment]
Yes we haven't updated the SmDevice model recently as that hasn't been used much but we will update these yes.

**Comment by speed2048** [comment]
Hi Daniel,

Do you have an ETA when a new release will be available?

**Comment by danielabbatt** [comment]
I don't for this particular update, we're updating some models on Monday so it might be included this week.
The best thing to do is to submit a pull-request for consideration, that'll expedite it somewhat.

**Comment by speed2048** [comment]
If you don't get to this on Monday, I can do a pull-request next week.
