### ISSUE TITLE
Get API version number

### ISSUE THREAD

**Issue by WestconSamaDevTeam** [panoramicdata/Meraki.Api#104]
In the official Python implementation by Cisco you can access the API version:
client._session._version

In c# this is not possible because this would be a private property on a private object.
But i'd still like to see an ApiVersion public string so i could query this.

**Comment by danielabbatt** [comment]
@WestconSamaDevTeam are you asking to get the version of the client library, or the version of the API being queried? Which of course can be different...

**Comment by WestconSamaDevTeam** [comment]
Preferrably both.
It is just informational, but it may help in troubleshooting if Cisco updates the API and something gets broken as a result of that.

**Comment by WestconSamaDevTeam** [comment]
@danielabbatt 
The only way that I currently know of is using the Meraki Python library from Cisco and then connect with a client instance and then use the value of: client._session._version

But to be honest this was quite some time ago (a year or so) and they have been upgrading their Python library quite a bit since 
 then, but it still seems to work.

**Comment by danielabbatt** [comment]
@WestconSamaDevTeam understood. It's not clear to me whether this is the client or server version being returned by the Python library.

The NuGet package has been updated to include an ApiClientVersion on the MerakiClient as of https://www.nuget.org/packages/Meraki.Api/1.31.46
