### ISSUE TITLE
Issue when searching clients by MAC address

### ISSUE THREAD

**Issue by rlouch2** [panoramicdata/Meraki.Api#109]
When using the /networks/{networkid}/clients/{mac} address or /networks/{networkid}/clients?mac={mac} it seems that the url is being HTTP encoded and all of the ":" are replaced. This is causing all of the clients to not be found and throwing exceptions in the code for a 404 not found.

I can get additional logging if you need to track it down, or if you can point me in the right direction I can fix it and submit a pull request for it too.

**Comment by danielabbatt** [comment]
Ah yes this could be down to refit encoding the URLs which I would expect it to really. 
It implies that the Meraki API server does not URL decode these parameters when they contain characters that are usually URL encoded.

https://learn.microsoft.com/en-us/dotnet/api/system.net.webutility.urlencode?view=net-8.0#system-net-webutility-urlencode(system-string)

We'll look into how we might work around this and if you get any insight into what the Meraki API will allow for these colons in terms of encoding that could be helpful.

**Comment by rlouch2** [comment]
I figured out the cause/solution within Refit. I'll get a pull request built up for you.

**Comment by danielabbatt** [comment]
Ah great well found. Glad it works for you.
