### ISSUE TITLE
GetOrganizationsAsync() returns data that doesn't exist in the API call

### ISSUE THREAD

**Issue by WestconSamaDevTeam** [panoramicdata/Meraki.Api#110]

**Comment by danielabbatt** [comment]
Hi, can you comment on why you opened this and then closed without note? What data was being returned that was not contained in the curl response? We try to include everything that comes back including undocumented properties etc. I don't believe we make anything up..., But if we are that should be fixed or documented.

**Comment by WestconSamaDevTeam** [comment]
I couldn't delete it.
It turns out that the Cisco documentation is incomplete.
Under some circumstances the API returns more data than what is documented. My first few test cases didn't account for these circumstances so curl wouldn't return the data so i thought this software was in error. But some expanding and testing later it showed that the extra data does get returned by the API even in Curl, so in this case Cisco's documentation is in error, your software is spot on.
