### ISSUE TITLE
Endpoint support:   /organizations/{organizationId}/wireless/devices/ethernet/statuses

### ISSUE THREAD

**Issue by davidnmbond** [panoramicdata/Meraki.Api#68]
I realise that it is in early access at present, but we have a requirement for the endpoint documented here to be supported:

-  [https://developer.cisco.com/meraki/api-latest/#!get-organization-wireless-devices-ethernet-statuses](https://developer.cisco.com/meraki/api-latest/#!get-organization-wireless-devices-ethernet-statuses)

The endpoint is: organizations/{organizationId}/wireless/devices/ethernet/statuses

Please could you add such support?

**Comment by danielabbatt** [comment]
Shouldn't be a problem. Depending on whether the customer has this feature available the call may or may not work of course, but that would as expected.

**Comment by stashjones** [comment]
This is done, in pull request #69
