### ISSUE TITLE
Getting Refit.APIException

### ISSUE THREAD

**Issue by speed2048** [panoramicdata/Meraki.Api#97]
When I call the following Meraki API

`
string networkID = "N_xxxxxxxxxxxxxxxxxxx";

using var merakiClient = new MerakiClient(new MerakiClientOptions

           {
 
               ApiKey = XCiscoMerakiAPIKey
 
           });

           var result = await merakiClient
                .Networks
                .Clients
                .GetNetworkClientsAsync(networkID)
                .ConfigureAwait(false);
`

I get the following exception:

**Refit.ApiException: Response status code does not indicate success: 400 (Bad Request).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288**
--- End of stack trace from previous location ---
   at XPORestAPI.Controllers.MerakiController.GetDeviceInfo(String XCiscoMerakiAPIKey, String networkId, String deviceName) in C:\Users\mcmil\source\repos\XPORestAPI\XPORestAPI\Controllers\MerakiController.cs:line 90
...

I am using Merali.API Version 1.30.7 and Visual Studio 2022 Version 17.5.0 Preview 6.0.

I looked at the Refit repository and there are references to this exception but not sure if the solution applies here. I have used other Meraki APIs and they do have any issues.

**Comment by danielabbatt** [comment]
The 400 is being returned by the Meraki API which is notoriously unhelpful. If the network Id is a Configuration Template I'd expect you to be getting a 400.
You may be able to look at the Refit ApiException and look at the Content property which may include some body content from Meraki indicating the problem.
Also try the same request using Postman and see what response you get.
Ultimately the 400 is coming from Meraki and not a feature of the API client itself.

**Comment by speed2048** [comment]
Hi Daniel,

The Content property contained 'Invalid device type'. I had passed the SYSTEM Manager Network ID as I discovered will return this error.

Thanks for your help.

**Comment by danielabbatt** [comment]
Glad you got to the bottom of it!
